# Weight Limits (MMA)
WEIGHT_LIMIT_ATOM = 47.6272
WEIGHT_LIMIT_STRAW = 52.1631
WEIGHT_LIMIT_FLY = 56.699
WEIGHT_LIMIT_BANTAM = 61.235
WEIGHT_LIMIT_FEATHER = 65.7709
WEIGHT_LIMIT_LIGHT = 70.3068
WEIGHT_LIMIT_S_LIGHT = 74.8427
WEIGHT_LIMIT_WELTER = 77.1107
WEIGHT_LIMIT_S_WELTER = 79.3786647
WEIGHT_LIMIT_MIDDLE = 83.9146
WEIGHT_LIMIT_S_MIDDLE = 88.4505
WEIGHT_LIMIT_L_HEAVY = 92.9864
WEIGHT_LIMIT_CRUISER = 102.058
WEIGHT_LIMIT_HEAVY = 120.202
WEIGHT_LIMIT_S_HEAVY = None


# Weight Classes (MMA)
WEIGHT_CLASS_ATOM = "atom"
WEIGHT_CLASS_STRAW = "straw"
WEIGHT_CLASS_FLY = "fly"
WEIGHT_CLASS_BANTAM = "bantam"
WEIGHT_CLASS_FEATHER = "feather"
WEIGHT_CLASS_LIGHT = "light"
WEIGHT_CLASS_S_LIGHT = "s_light"
WEIGHT_CLASS_WELTER = "welter"
WEIGHT_CLASS_S_WELTER = "s_welter"
WEIGHT_CLASS_MIDDLE = "middle"
WEIGHT_CLASS_S_MIDDLE = "s_middle"
WEIGHT_CLASS_L_HEAVY = "l_heavy"
WEIGHT_CLASS_CRUISER = "cruiser"
WEIGHT_CLASS_HEAVY = "heavy"
WEIGHT_CLASS_S_HEAVY = "s_heavy"
WEIGHT_CLASSES = [
    WEIGHT_CLASS_ATOM,
    WEIGHT_CLASS_STRAW,
    WEIGHT_CLASS_FLY,
    WEIGHT_CLASS_BANTAM,
    WEIGHT_CLASS_FEATHER,
    WEIGHT_CLASS_LIGHT,
    WEIGHT_CLASS_S_LIGHT,
    WEIGHT_CLASS_WELTER,
    WEIGHT_CLASS_S_WELTER,
    WEIGHT_CLASS_MIDDLE,
    WEIGHT_CLASS_S_MIDDLE,
    WEIGHT_CLASS_L_HEAVY,
    WEIGHT_CLASS_CRUISER,
    WEIGHT_CLASS_HEAVY,
    WEIGHT_CLASS_S_HEAVY,
]


# Sport
SPORT_MMA = "mma"
SPORT_KNUCKLE_MMA = "knuckle_mma"
SPORT_BOX = "box"
SPORT_KNUCKLE_BOX = "knuckle_box"
SPORT_KICK = "kick"
SPORT_MUAY = "muay"
SPORT_KARATE = "karate"
SPORT_SANDA = "sanda"
SPORT_LETHWEI = "lethwei"
SPORT_GRAPPLE = "grapple"
SPORT_SHOOT = "shoot"
SPORT_WRESTLE = "wrestle"
SPORT_SAMBO = "sambo"
SPORT_VALE = "vale"
SPORT_JUDO = "judo"
SPORT_COMBAT_JJ = "combat_jj"
SPORT_CUSTOM = "custom"
SPORTS = [
    SPORT_MMA,
    SPORT_KNUCKLE_MMA,
    SPORT_BOX,
    SPORT_KNUCKLE_BOX,
    SPORT_KICK,
    SPORT_MUAY,
    SPORT_KARATE,
    SPORT_SANDA,
    SPORT_LETHWEI,
    SPORT_GRAPPLE,
    SPORT_SHOOT,
    SPORT_WRESTLE,
    SPORT_SAMBO,
    SPORT_VALE,
    SPORT_JUDO,
    SPORT_COMBAT_JJ,
    SPORT_CUSTOM,
]


# Billing of the match
BILLING_MAIN = "main"
BILLING_CO_MAIN = "co_main"
BILLING_MAIN_CARD = "main_card"
BILLING_PRELIM_CARD = "prelim_card"
BILLING_POSTLIM_CARD = "postlim_card"
BILLINGS = [
    BILLING_MAIN,
    BILLING_CO_MAIN,
    BILLING_MAIN_CARD,
    BILLING_PRELIM_CARD,
    BILLING_POSTLIM_CARD,
]


# Status of the match
STATUS_WIN = "win"
STATUS_LOSS = "loss"
STATUS_CANCELLED = "cancelled"
STATUS_DRAW = "draw"
STATUS_UPCOMING = "upcoming"
STATUS_NC = "nc"
STATUS_UNKNOWN = "unknown"
STATUSES = [
    STATUS_WIN,
    STATUS_LOSS,
    STATUS_CANCELLED,
    STATUS_DRAW,
    STATUS_UPCOMING,
    STATUS_NC,
    STATUS_UNKNOWN,
]


# Ending Method
METHOD_KO_TKO = "ko/tko"
METHOD_SUBMISSION = "submission"
METHOD_RETIREMENT = "retirement"
METHOD_FORFEIT = "forfeit"
METHOD_CORNER_STOPPAGE = "corner"
METHOD_DOCTOR_STOPPAGE = "doctor"
METHOD_DQ = "dq"
METHOD_DECISION_UNANIMOUS = "decision_unanimous"
METHOD_DECISION_MAJORITY = "decision_majority"
METHOD_DECISION_SPLIT = "decision_split"
METHOD_DECISION_TECHNICAL = "decision_technical"
METHOD_DECISION_POINTS = "decision_points"
METHOD_DECISION = "decision"
METHOD_TIMELIMIT = "timelimit"
METHOD_EXHIBITION = "exhibition"
METHOD_ILLEGAL = "illegal"
METHOD_INJURY = "injury"
METHOD_BOTH = "both"
METHOD_DOPING = "doping"
METHOD_OFFICIAL_ERROR = "official_error"
METHOD_INCIDENT = "incident"
METHOD_OVERWEIGHT = "over_weight"
METHOD_DOUBLE_KO = "double_ko"
METHOD_WINONLY = "winonly"
METHOD_OVERTURNED = "overturned"
METHOD_UNKNOWN = "unknown"


# Round Format Types
ROUND_FORMAT_TYPE_REGULAR = "regular"
ROUND_FORMAT_TYPE_UNLIM_ROUNDS = "unlim_rounds"
ROUND_FORMAT_TYPE_UNLIM_ROUND_TIME = "unlim_round_time"
ROUND_FORMAT_TYPE_ROUND_TIME_UNKNONW = "round_time_unknown"


# Division of the match
DIVISION_PRO = "pro"
DIVISION_AM = "am"
DIVISIONS = [
    DIVISION_PRO,
    DIVISION_AM,
]


# Expected values for "not available"
VALUES_NOT_AVAILABLE = ["n/a", "na"]
